# fly.toml app configuration file generated for paint-library on 2023-08-14T12:20:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "paint-library"
primary_region = "sea"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000
min_machines_running = 0
processes = ["app"]
